[build]
  publish = "build"
  command = "npm install -C functions && CI=false npm run build"

[functions]
  directory = "functions"
  node_bundler = "esbuild"

[functions."*"]
  timeout = 26
