[build]
  publish = "build"
  command = "CI=false npm run build"

[functions]
  directory = "functions"
  node_bundler = "esbuild"
  external_node_modules = ["@google/generative-ai"]

[functions."*"]
  timeout = 26
