[build]
  publish = "build"
  command = "CI=false npm run build"

[functions]
  directory = "functions"
  node_bundler = "esbuild"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[functions."*"]
  timeout = 26
